services:
  app:
    container_name: rest-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5433/saboresdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Equili2000
    networks:
      - rest-api-network
  db:
    container_name: postgresdb
    image: postgres:16.4-alpine3.20
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Equili2000
      POSTGRES_DB: saboresdb
    networks:
      - rest-api-network
    healthcheck:
      # Use the CMD-SHELL command to check the health
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      # Set the interval to 10 seconds
      interval: 10s
      # Set the timeout to 5 seconds
      timeout: 5s
      # Set the retries to 5
      retries: 5
    volumes:
      - saboresdb-data:/var/lib/postgresql/data

volumes:
  saboresdb-data:

networks:
  rest-api-network: